export {
  registerBodySchema,
  loginBodySchema,
  updateMeBodySchema,
  onboardingBodySchema,
  verifyEmailBodySchema,
  resendVerificationBodySchema,
  forgotPasswordBodySchema,
  resetPasswordBodySchema,
  changePasswordBodySchema,
  changeEmailRequestBodySchema,
  changeEmailConfirmBodySchema,
  changeEmailCancelBodySchema,
  deleteAccountBodySchema,
  recoverAccountBodySchema,
  cancelDeletionBodySchema,
  SUPPORTED_LOCALES,
} from "@lifeos/shared";

export type {
  RegisterBody,
  LoginBody,
  UpdateMeBody,
  OnboardingBody,
  OnboardingResponse,
  VerifyEmailBody,
  ResendVerificationBody,
  ForgotPasswordBody,
  ResetPasswordBody,
  ChangePasswordBody,
  ChangeEmailRequestBody,
  ChangeEmailConfirmBody,
  ChangeEmailCancelBody,
  DeleteAccountBody,
  RecoverAccountBody,
  CancelDeletionBody,
  UserResponse,
  UserStatus,
  SupportedLocale,
  AuthResponse,
  MeResponse,
} from "@lifeos/shared";
